
import pygame
from pygame.locals import *
import sys

from storage.gameVars import *
from game_manager import Game
from storage.debugUtitlity import *
from entities.pickups import HealthPack

pygame.init()
clock = pygame.time.Clock()

screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Alyss")

game = Game(screen)

temp = False
while True:
    # regular pygame exit check
    for event in pygame.event.get():
        if event.type == QUIT:
            pygame.quit()
            sys.exit()
        
        game.dialogue.handle_input(event)

    # obselete boss code
    if game.miniBoss1.dead and game.miniBoss2.dead and not game.has_boss_activated:
        game.boss.activate()
        game.has_boss_activated = True

    game.boss.checkDashDamage(game.player)

    if game.boss.deadCheck():
        game.boss.takeDamage(9999)

    # player and enemy interaction...
    hits = pygame.sprite.spritecollide(game.player, game.enemy_sprites, False)

    for enemy in hits:
        if game.player.isDashing:
            enemy.takeDamage(1)
        elif hasattr(enemy, "isHarmful") and enemy.isHarmful:
            game.player.takeDamage(1, 60)

    # player and friendly interaction
    for sprite in game.friendly_sprites:
        if isinstance(sprite, HealthPack):
            if game.player.rect.colliderect(sprite.rect):
                if game.player.hp < 5:
                    game.player.takeDamage(-1, 0)
                    sprite.kill()
    
    # interaction with interactables
    hits2 = pygame.sprite.spritecollide(game.player, game.interactables, False)
    for obj in hits2:
        if game.player.isDashing:
            obj.takeDamage(1)

    # rudimentary screen shake
    game.update_screen_shake()
    offset = game.screen_shake_offset

    game.update_camera()
    screen.fill((255, 255, 255))

    game.friendly_sprites.update()
    game.enemy_sprites.update()
    game.ui_sprites.update()
    game.interactables.update()

    # TODO: smart loading AND smart enemy rendering
    for room in game.rooms.values():
        room.update()
        game.tileHandler.draw(room, game.camera)

    for s in game.ui_sprites:
        screen.blit(s.image, s.rect.topleft - (vec(s.image.get_size()) - vec(s.rect.size)) / 2 + offset)
    for s in game.interactables:
        screen.blit(s.image, s.rect.topleft - game.camera + vec(WIDTH / 2, HEIGHT / 2) - (vec(s.image.get_size()) - vec(s.rect.size)) / 2 + offset)
    for s in game.friendly_sprites:
        screen.blit(s.image, s.rect.topleft - game.camera + vec(WIDTH / 2, HEIGHT / 2) - (vec(s.image.get_size()) - vec(s.rect.size)) / 2 + offset)
        # draw_debug_rect(screen, s.rect, game.camera)
    for s in game.enemy_sprites:
        screen.blit(s.image, s.rect.topleft - game.camera + vec(WIDTH / 2, HEIGHT / 2) - (vec(s.image.get_size()) - vec(s.rect.size)) / 2 + offset)
        # draw_debug_rect(screen, s.rect, game.camera)

    # dialogue rendering!
    game.dialogue.update()
    game.dialogue.draw()


    if (not temp):
        game.dialogue.start([
            {"text": "The sign out front is busted...", "speaker": "player"},
            {"text": "Is this the Mountain trail?", "speaker": "player"}
        ])
        temp = True

    # TODO
    game.boss.drawLasers(screen)
    pygame.display.update()
    game.gameTime += 1
    clock.tick(FPS)

    # room = game.get_current_room()
    
    # print("pos:", game.player.pos)
    # print("rect.center:", game.player.rect.center)
    # print("rect.topleft:", game.player.rect.topleft)
'''
CREDITS:
Generative AI (ChatGPT) was utilized to speed up the busy work of the code in order to finish within a timely matter, including creating the boss, mini-boss code, as well as the animSets (they would take very very long to make by hand). Some stylizing effects such as the screen shake as well as the sine wave movement code was generated by ChatGPT in order to polish up the game.

The animation system, class system is my work, and the player and basic enemy is of notably our creation. We have tweaked them numerous times, giving the Reddies complex AI that enhances the game difficulty to notable levels. We have also thought of the dash attack system, inspired by games such as Just Shapes and Beats (JSAB), and Celeste.

Furthermore, we fully understand the generative AI's code in this work, evident as we are able to tweak the code and fix bugs in the generated code, such fixing the bug when the boss did not have a kill timer to remove itself from being rendered after hp hits 0.

Codio's X Server extension is used to obtain a visual screen for the application.

Fun Fact: The assets are completely original, with my partner creating over 60 or so 8 by 8 pixel art sprites for the game.
'''